spring:
  profiles:
    active: dev
---
spring:
  data.mongodb:
    uri: mongodb://root:123456789@localhost:27017/learn?authSource=admin
  config:
    activate:
      on-profile: dev
---
spring:
  data.mongodb:
    uri: mongodb://root:123456789@localhost:27017/learn?authSource=admin
  config:
    activate:
      on-profile: nonprod
---
spring:
  data.mongodb:
    uri: mongodb://root:123456789@localhost:27017/learn?authSource=admin
  config:
    activate:
      on-profile: prod
---
spring:
  profiles: test
